name: Build

on:
  workflow_dispatch:
  push:
    branches: newopenjk

jobs:

  vs2013_xp:
    name: Build VS 2013, Windows XP
    runs-on: [self-hosted, windows]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -A Win32 -T v120_xp

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: Install
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --install . --prefix install

    - name: Upload Install
      uses: actions/upload-artifact@v2
      with:
        name: Windows Build
        path: ${{runner.workspace}}/build/install


