name: Build

on:
  workflow_dispatch:
  push:
    branches: newopenjk

jobs:

  vs2013_xp:
    name: Build VS 2013, Windows XP, ${{ matrix.build_type }}
    runs-on: [self-hosted, windows]
    strategy:
      matrix:
        build_type: [Release, RelWithDebInfo]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: powershell
      working-directory: ${{runner.workspace}}/build
      run: cmake $env:GITHUB_WORKSPACE -A Win32 -T v120_xp

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: powershell
      run: cmake --build . --config ${{ matrix.build_type }}

    - name: Install
      working-directory: ${{runner.workspace}}/build
      shell: powershell
      run: cmake --install . --prefix install

    - name: Upload Install
      uses: actions/upload-artifact@v2
      with:
        name: Windows Build ${{ matrix.build_type }}
        path: ${{runner.workspace}}/build/install


